// i18n: employee feature strings
export const employeeStrings = {
  page: {
    title: "Quản lý nhân sự",
    description: "Danh sách cán bộ, giảng viên, nhân viên",
    addButton: "Thêm nhân sự",
    searchPlaceholder: "Tìm kiếm theo tên, mã NV, email...",
    emptyMessage: "Không có nhân sự nào",
  },
  detail: {
    title: "Thông tin nhân sự",
    notFound: "Không tìm thấy",
    notFoundDescription: "Không tìm thấy thông tin nhân sự.",
    editTooltip: "Chức năng chỉnh sửa đang được phát triển",
    personalInfoTitle: "Thông tin cá nhân",
    careerInfoTitle: "Thông tin nghề nghiệp",
  },
  columns: {
    staffCode: "Mã NV",
    fullName: "Họ tên",
    gender: "Giới tính",
    phone: "Điện thoại",
    email: "Email",
    orgUnit: "Đơn vị",
    workStatus: "Trạng thái",
  },
  form: {
    saveLabel: "Lưu nhân sự",
    savingLabel: "Đang lưu...",
    personalInfoTitle: "Thông tin cá nhân",
    careerInfoTitle: "Thông tin nghề nghiệp",
    fields: {
      fullName: "Họ tên",
      dob: "Ngày sinh",
      gender: "Giới tính",
      nationalId: "Số CCCD/CMND",
      hometown: "Quê quán",
      address: "Địa chỉ",
      email: "Email",
      phone: "Số điện thoại",
      isForeigner: "Là người nước ngoài",
      staffCode: "Mã nhân viên",
      positionTitle: "Chức danh hiện tại",
      orgUnit: "Đơn vị công tác",
      orgUnitPlaceholder: "Chọn đơn vị công tác...",
      salaryGrade: "Bậc lương",
      salaryGradePlaceholder: "Chọn bậc lương...",
      workStatus: "Trạng thái làm việc",
      contractStatus: "Trạng thái hợp đồng",
      educationLevel: "Trình độ văn hóa",
      trainingLevel: "Trình độ đào tạo",
      academicTitle: "Chức danh nghề nghiệp",
      academicRank: "Học hàm",
    },
  },
  delete: {
    title: "Xóa nhân sự",
    confirmPrefix: "Bạn có chắc muốn xóa nhân sự",
    success: "Đã xóa nhân sự",
  },
  detailLabels: {
    fullName: "Họ tên",
    dob: "Ngày sinh",
    gender: "Giới tính",
    nationalId: "CCCD/CMND",
    hometown: "Quê quán",
    address: "Địa chỉ",
    email: "Email",
    phone: "Điện thoại",
    orgUnit: "Đơn vị công tác",
    positionTitle: "Chức danh",
    workStatus: "Trạng thái",
    contractStatus: "Hợp đồng",
    educationLevel: "Trình độ văn hóa",
    trainingLevel: "Trình độ đào tạo",
    academicTitle: "Chức danh nghề nghiệp",
    academicRank: "Học hàm",
  },
} as const;
