export { loginSchema, type LoginInput } from "./auth";
export {
  paginationSchema,
  type PaginationQuery,
  idParamSchema,
  type IdParam,
  employeeIdParamSchema,
  type EmployeeIdParam,
} from "./common";
export {
  createContractTypeSchema,
  type CreateContractTypeInput,
  updateContractTypeSchema,
  type UpdateContractTypeInput,
  createAllowanceTypeSchema,
  type CreateAllowanceTypeInput,
  updateAllowanceTypeSchema,
  type UpdateAllowanceTypeInput,
  createSalaryGradeSchema,
  type CreateSalaryGradeInput,
  updateSalaryGradeSchema,
  type UpdateSalaryGradeInput,
  createSalaryGradeStepSchema,
  type CreateSalaryGradeStepInput,
  updateSalaryGradeStepSchema,
  type UpdateSalaryGradeStepInput,
  createTrainingCourseTypeSchema,
  type CreateTrainingCourseTypeInput,
  updateTrainingCourseTypeSchema,
  type UpdateTrainingCourseTypeInput,
} from "./config";
